 
on:
    pull_request_target:
     branches: [ master ]
     types: [opened, labeled, unlabeled, edited, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-latest
    name: Check PR has valid OCAs
    steps:
    - name: Check PR has valid OCAs
      uses: yelabbas/check-oca
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        valid-labels: 'OCA signed'
        pull-request-number: '${{ github.event.pull_request.number }}'
